### ISSUE TITLE
Outstanding Concerns about Continuum Opacities

### ISSUE THREAD

**Issue by mabruzzo** [ajwheeler/Korg.jl#12]
This issue is being created as place to record some outstanding concerns about currently implemented continuum opacities. For the most part, these concerns shouldn't necessarily preclude their usage.

These concerns include:
 - The minimum wavelength at which we can currently compute He⁻ free-free opacity is 5063 Å.
 - I'm a little concerned about the bound-free opacities at really long wavelengths (say ≳ 4.45 microns), where our approximation of the summation with an integral becomes more aggressive than what Gray (2005) recommends.
-  I'm a little concerned about the differences in the bound-free opacities from MOOG. We use the same approach (described by Kurucz 1970), but with 2 differences and I'm concerned that they know something that we don't. These differences include: 
    1. MOOG seems to entirely ignore the opacity contributions of transitions originating from higher energy levels (which we use the integral approximation for). 
    2. MOOG uses a completely different table to compute the bound-free opacity for contributions originating from the ground state (this latter point is only relevant for wavelengths at or below 912 Å)
 - If we ever enforce a cuttoff energy level in our partition functions, it might be important to account for this in our bound-free opacities (this may actually have something to do with a difference highlighted in the previous bullet point).
 - I'm not extremely confident that our He⁻ free-free opacity is accurate. The uncertainties in the references values are comparable to the magnitude of the reference values. I've got part of a test written to help improve our confidence, but I'm not sure we'll ever be as confident about its correctness as I am about H⁻ bf, H⁻ ff, H I bf, or H I ff.
 - We don't currently have a test for the electron scattering opacity. It may not be necessary since the function is a single line featuring just a multiplication and a division. 
 - We don't have tests checking the accuracy of the He II ff opacities. However, the fact that these calculations wrap the same functions that are used for the H I bf and H I ff calculations definitely instills some confidence.

**Comment by ajwheeler** [comment]
4.45 microns is a pretty big wavelength.  APOGEE, for example, extends to less that 2 microns.  It's great to have all this written down, though.

**Comment by mabruzzo** [comment]
Yeah, I kind of assumed that was the case. It seems firmly in the mid-infrared regime

**Comment by ajwheeler** [comment]
Summarizing current status of these things for posterity:

- **on He minus free-free:** Here is a plot showing a some of the most important sourced of absorption at the solar photosphere.  As you can see, He- ff is pretty subdominant (though not nearly as much so as many other mechanisms).  That doesn't mean this it isn't worth extending into the blue and UV, but it's very low priority.
![download-1](https://user-images.githubusercontent.com/711963/190704186-748924d9-8a3c-453c-b2e6-4c4efb82be4f.png)
- **On bf absorption past 4.5 microns:**. If we try to extend into the mid IR we should take another look at this.
- **On bf absorption contra MOOG**: I don't think this is worth worrying about.
- **On bf absorption and truncating U**: this is on my radar when investigating U truncation/the occupation probability formalism (which is important above 10,000K and only for H and *maybe* the lighter alkalis).  Barklem's routines for H lines and bf absorption handle this in full detail.

**Comment by ajwheeler** [comment]
I'm closing this as it no longer represents good list of areas in need of improvement.
