### ISSUE TITLE
Truncated Balmer lines

### ISSUE THREAD

**Issue by segasai** [ajwheeler/Korg.jl#140]
Hi, 

Sorry for spamming in several issues.
This is related to #139 but in this case I looked at Balmer lines for teff=8000, logg=5.00, feh=-2.00 ,alpha/fe=0 vs PHOENIX.
And the Balmer lines are truncated. 
![compar1](https://user-images.githubusercontent.com/109513/201498465-7cbb86f5-78e0-4030-a279-7d0d19bbe37b.png)
If I had to guess there is some sort of window for the line that is used to compute the opacities.
Is it a bug or I need to change some parameter to fix that ? 

Thanks
        S

**Comment by ajwheeler** [comment]
Thanks!  This is a bug in that the parameter you need to tweak isn't actually exposed to the user.  #141 fixes that, and makes the window size larger by default, so that you wouldn't need to tweak it in the first place for these inputs.

**Comment by mabruzzo** [comment]
PR #141 fixed this, right? Can we close this issue?

**Comment by ajwheeler** [comment]
I'm going to add an item to the big TODO issue so that automatic windowing doesn't drop off the radar forever, but I don't think it makes sense to work on now because it's not trivial and the hydrogen lines seem to be the part of the code most in need other changes.
