### ISSUE TITLE
behaviour near edges of synthesized spectrum 

### ISSUE THREAD

**Issue by segasai** [ajwheeler/Korg.jl#148]
Hi, 

I'm not 100% sure it is a bug or not, but it is certainly unexpected. 
I' ve been resynthesizing my MARCS grid with a fuller line-list, and because of its size I've been doing the synthesis in 500A chunks, while making sure my line-list has lines from left_edge-200A to right_edge+200A. 
While stiching the synthesized spectra, I do notice the jump at the stitch point (in this case the 3500-4000 and 4000-4500 were synthesized separately): 
![image](https://user-images.githubusercontent.com/109513/202700833-aa5bf69d-14f2-4a06-8e3e-9bb24870ec76.png)

Is it expected ? 
From my cursory reading of 
https://github.com/ajwheeler/Korg.jl/blob/f80f2eeff4eccac7767fa9f28c4298e1c467e1ea/src/line_absorption.jl#L60
 it seems that all the lines that have a window overlapping with the currently synthesized wavelength range  should be  used. 

In fact I've done a clearer test.
I take a single line list covering 3300A to 4200A and 
then synthesize the spectra from 3900 to 3980 and then from 3980 to 4060 and I do get the jump in the wing of the CaK line
![image](https://user-images.githubusercontent.com/109513/202707735-5ace6c79-0302-4c6e-9f71-3a58aff2bac4.png)

So it's clearly not caused by a line-list. 

In fact  for some reason if I synthesize from 3900 to 3975 vs 3975 to 4050 the jump disappears. 
If it matters, this is the atmosphere: p5750_g+3.0_m0.0_t02_ae_z-0.25_a+0.40_c+0.00_n+0.00_o+0.40_r+0.00_s+0.00.mod

I briefly looked at the behaviour of window boundaries lb, ub in line_absorption.jl, they seem to be sensible, so something else must be going awry.

**Comment by segasai** [comment]
Ah, I discovered the line_buffer option. It seems I just need to increase it here.

**Comment by ajwheeler** [comment]
No worries, let me know if you think that I should consider increasing the default buffer size.

**Comment by segasai** [comment]
It is hard to tell. I think many strong lines are certainly wider than 10A, so TBH 100A seems like a safer choice to me. But I also don't really know where most of the time is spent in the code. Is it in solving for population of different ionization states or evaluating actual line profiles.

**Comment by ajwheeler** [comment]
The line profiles are in most cases the bottleneck, thus the small default buffer.

**Comment by segasai** [comment]
But evaluating the line-width/window for each line comes before that, so if lines are not contributing to a given wavelength range, their profiles won't be evaluated.

**Comment by segasai** [comment]
Out of curiousity, I've checked the time needed as a function of the interval length (+/-) and buffer_size (starting from 6500 A and with the full line-list)

Interval Buffer Time
1 10 5.2
1 30 7.3
1 100 20.5
1 300 53.3
10 10 5.4
10 30 8.0
10 100 20.3
10 300 54.8
100 10 15.7
100 30 19.2
100 100 30.8
100 300 65.1
1000 10 120.6
1000 30 124.5
1000 100 136.2
1000 300 167.8
3000 10 321.0
3000 30 324.1
3000 100 328.1
3000 300 343.1

It seems that basically  the time is just linear interval length + buffer_size. 
That's kinda a bit weird given what you said as for the majority of these cases with big buffer the line_profile won't be actually evaluated on the majority of lines outside the interval.
