### ISSUE TITLE
Should all equilibrium constants be calculated on the fly?

### ISSUE THREAD

**Issue by ajwheeler** [ajwheeler/Korg.jl#159]
#155 introduces new polyatomic molecules.  Instead of interpolating from precomputed tables of equilibrium values, it computes them on the fly from the exomol partition function and CCCBDB atomization energies.

I think it might be wise to do this for all molecules.  Here's why.
- The Barklem and Collet atomic partition functions have minor inaccuracies.  Somehow, when I realized this, I didn't make the connection that the problem would affect their equilibrium constants, but of course it will. This could also be addressed by recomputing the equilibrium constants myself and re-saving them to interpolate from, but we should do something about it.
- It will simplify the code.  I would expect the total number of lines to shrink, and I think this is a worthy goal.
- I will also make adding more molecules/swapping out data easier, as it removes the need to precompute and save things.

possibles cons:
- It might be slower.  I would be surprised if it raised runtime by more than a few percent at the most, and it might not raise it at all, but these things are hard to predict.
- It would involve another API change.  The new API would be slightly less complex (there would be an D00 dict instead of a K dict), and swapping out dissociation energies would simpler.  but Sarah would still have to change her code again.

**Comment by andycasey** [comment]
It's possible that I don't fully appreciate all the positive things to computing them on the fly, but from this summary I think the possible cons do not outweigh the pros. But I also think you're in a better position to judge this. Would having a script to compute equilibrium constants and save them to a file before Korg runs for the first time be a suitable compromise? 

And if you do decide to calculate them on the fly, then don't worry that the proposed API change would require Sarah to update her code. It's a reasonable side effect of doing something new.

**Comment by ajwheeler** [comment]
> It's possible that I don't fully appreciate all the positive things to computing them on the fly, but from this summary I think the possible cons do not outweigh the pros. 

You probably aren't.  I have a somewhat extreme desire to simplify code. You've convinced me not to worry about this at least until I touch that part of the code again.
