### ISSUE TITLE
Inaccuracies in model atmosphere interpolation

### ISSUE THREAD

**Issue by ajwheeler** [ajwheeler/Korg.jl#164]
Interpolating model atmospheres introduces error.  In some parts of parameter space, it is trivial amount, but in others it is significant.  These plots show the error on synthesized rectified spectrum from interpolation.  They were created by interpolating atmospheres at the points exactly mid-way from the grid points, then interpolating back to the grid (credit to Carlos Allende Prieto for originally coming up with this).  The first plot shows the standard deviation of the difference between the spectra synthesized with the exact model atmosphere and the interpolated one.  The second plot shows the worst-case error, the discrepancy at the wavelength at which it is largest. (The largest discrepancies are at line cores, so this is very relevant.) 
![image](https://user-images.githubusercontent.com/711963/214636851-5f533cfb-cffe-45f0-baae-da41a3aad566.png)
![image](https://user-images.githubusercontent.com/711963/214636896-5ffd38c1-54a0-4b8a-ad1b-72fdf552305f.png)

Above 4250K or so, these error are small enough to ignore for most purposes, but for cooler stars they may be a big problem.  I suspect that spectra of cool stars simply change quickly as a function of Teff and logg, making interpolation fundamentally difficult without a denser grid.  Interpolating synthesized spectra rather than model atmospheres sometimes performs better, sometimes  worse, but doesn't make a substantial difference and is much more expensive.

It may be that some existing method of model atmosphere interpolation would beat our current implementation. It may also be that if Korg were to solve for the electron number density rather than taking it as fixed when solving for chemical equilibrium it would lessen error introduced by interpolation.

**Comment by ajwheeler** [comment]
#179 doesn't effect this.
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/388eac73-840b-4cea-ad96-50ccb3891636)
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/d9b0196e-f0f1-48c8-8b75-201ff6b33e51)

**Comment by ajwheeler** [comment]
Relevant paper: https://arxiv.org/pdf/2306.06938.pdf https://github.com/cwestend/iNNterpol/tree/main/iNNterpol_MARCS

**Comment by ajwheeler** [comment]
Good news and bad news.  I thought to check the RMS error, rather than the std, and it makes things look a bit worse.  
<details>
<summary> plots with RMS instead of std with a similar colorbar to the above </summary>

![image](https://github.com/ajwheeler/Korg.jl/assets/711963/32c8849c-9164-4c5a-b475-2b3ff7522e0a)
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/fe0633d4-f1f2-4b6c-a924-e6d8e4ce4400)
</details>

The upside is that I messed around with using cubic instead of linear interpolation, and it (unsurprisingly) works better!  The reason I never did this in the first place, is because I started out with an atmosphere grid missing various values, so I was rolling my own interp.  The grid I ended up using is nice and regular, though.


![image](https://github.com/ajwheeler/Korg.jl/assets/711963/9671f50f-d94c-459d-a02b-860d1eb071bc)![image](https://github.com/ajwheeler/Korg.jl/assets/711963/c97fb428-d244-470e-ac40-a8416252a21a)
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/1b4e9dd3-8ffb-4266-893f-18d0de523dd9)![image](https://github.com/ajwheeler/Korg.jl/assets/711963/4c290c67-4c6f-4af9-82d4-862429d0b179)

It looks like cubic interpolation pushes the frontier of good interpolation from a bit over 4000 to a bit under 4000, which improves the situation for a huge fraction of, e.g. MWM stars.

**Comment by ajwheeler** [comment]
You might expect this test to give different results for APOGEE spectra than for high-res optical spectra.  Interestingly, the overall picture is about the same, but the transition from good to bad is much sharper.

![image](https://github.com/ajwheeler/Korg.jl/assets/711963/72a5d5aa-7356-4e44-8db3-b60e4e21743e)![image](https://github.com/ajwheeler/Korg.jl/assets/711963/fd731bde-199c-44fa-b427-e18f1133e09d)
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/a62f1288-d9e4-4b99-858a-532719fc1603)![image](https://github.com/ajwheeler/Korg.jl/assets/711963/b633ed53-c694-4c42-8475-8e85702101e9)

Interestingly, this seems to be driven by a systematic offset in the  pseudocontinuum, which is consistent with the temperatures being wildly messed up. This is for Teff=3000K, logg=4.5 (i.e. worst case).
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/a2841d00-1940-4c72-aee0-96068612716a)

@andycasey, I'm curious if you think this is worth implementing, or if we should hold out for something better?

**Comment by andycasey** [comment]
I'm puzzled by how a systematic offset in the pseudocontinuum is driving this!

If cubic interpolation of the model atmospheres does not add much cost penalty, then I think the benefit from better interpolation at cooler temperatures makes it worth it.

**Comment by andycasey** [comment]
With this cubic interpolation routine do we lose any grid boundaries? For example, can we still reliably interpolate up to the grid boundaries or can we only interpolate up to the second last grid point?

**Comment by ajwheeler** [comment]
We don't lose grid boundaries, it's just a matter of specifying what the second derivative should do.

I did some experiments where I replaces just one atmosphere variable with the uninterpolated one, and it turns that for cool stars, the problem is $\tau_{5000}$, not temperature!
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/28f3ed22-fef0-447c-96bf-b66801bc3e7e)

**Comment by ajwheeler** [comment]
By resampling all the atmospheres to the same $\tau_{5000}$ values (rather than a constant tau ros grid), I've improved things quite a bit again:
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/320bdeb1-82ff-432d-b869-9721bc3b7bfb)

Interestingly, you can kinda see the shape of the Kiel diagram in this plot.

**Comment by ajwheeler** [comment]
As of this comment, the most complete discussion of this can be found in this paper: https://ui.adsabs.harvard.edu/abs/2023arXiv231019823W/abstract

**Comment by ajwheeler** [comment]
Closing this issue as it is out-of-date and might mislead people.  The discussion in the paper linked above is the most up-to-date one, though note that the specialized metal-poor model atmosphere grid introduced in #291 is not discussed.
