### ISSUE TITLE
synthetic spectrum generated using python and julia 

### ISSUE THREAD

**Issue by fredifqh** [ajwheeler/Korg.jl#236]
I was trying to use Korg using python to get a synthetic spectrum. However, when comparing with the spectrum generated using julia, we see that they are different as shown in the attached figures. Any suggestion? 

The codes to generate the synthetic spectra are shown below:
`
% julia
> lines = read_linelist("linelist.vald", format="vald")
> itp = interpolate_marcs(7500, 4.)
> synt = synthesize(itp, lines, format_A_X(0), 3500, 9600, 1)
> figure(figsize=(12, 4))
> plot(synt.wavelengths, synt.flux*1e-8, label="test")
> savefig("synth_julia.png")
`

`%python
> from julia import Korg
> lines = Korg.read_linelist("linelist.vald", format="vald")
> itp = Korg.interpolate_marcs(7500, 4.)
> synt = Korg.synthesize(itp, lines, Korg.format_A_X(0), 3500, 9600, 1)
> plt.figure(figsize=(12, 4))
> plt.plot(synt.wavelengths, synt.flux*1e-8, label="test")
> plt.savefig('synth_python.png')`

![synth_julia](https://github.com/ajwheeler/Korg.jl/assets/7502567/7b8828dc-7721-4e19-bec6-ef96515fb1e0)
![synth_python](https://github.com/ajwheeler/Korg.jl/assets/7502567/eaa477d5-213f-40f4-9737-63ccf0032bde)

**Comment by andycasey** [comment]
In your Python code example, are `synt` and `synt_t7500_l4_f0` the same thing?

**Comment by fredifqh** [comment]
Yes, is the same.

**Comment by ajwheeler** [comment]
Hmm, in the julia case, it looks like only hydrogen lines (which are included whether or not they are present in the linelist) are present in the spectrum. Could you check the length of lines (‘len(lines)’ in python, ‘length(lines)’ in julia) to help narrow down where something it going wrong?

**Comment by fredifqh** [comment]
`%python
len(lines)
`
19236

**Comment by fredifqh** [comment]
Sorry, the problem was with that file. Now I made sure it is the same vald linelist file and it is working fine.

**Comment by ajwheeler** [comment]
No worries!
