### ISSUE TITLE
interpolated model atmospheres at low metallicity

### ISSUE THREAD

**Issue by ajwheeler** [ajwheeler/Korg.jl#258]
Currently, Korg will product interpolated model atmospheres down to [m/H]=-2.5 (the limit of the SDSS grid).  Ideally, we would be able to go lower.

On approach would be to extend the grid using atmospheres from MARCS which aren't in the SDSS grid.  Unfortunately, these have a lot of missing atmospheres.
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/de1a84e6-4d66-472f-803d-be5a62cca10c)
(**edit: I made a mistake making this plot (see below)**)
Things are better at higher [m/H], but still not great.  It's definitely feasible to patch this up somehow, but I'm exploring ATLAS as an alternative option. 

Unfortunately, extrapolation won't work either.  This shows what you get if you extrapolate down from -2.5 to -5 at Teff=5000K, logg=4.5.
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/48930bd2-b29f-4671-858f-851e341af75a)

**Comment by ajwheeler** [comment]
Here's a corrected visualization of which atmospheres are missing:
![image](https://github.com/ajwheeler/Korg.jl/assets/711963/46e56c43-bd38-42b5-a1a4-c2607d89c64c)

Quite a few, especially at low metallicities!

**Comment by willcerny** [comment]
Hi Adam,

Thanks for adding the alpha-enhanced model at [M/H] = -3  (here and in #291)! I was hoping for exactly that :)
I wanted to ask about whether there's a possibility of also adding Carbon-enhanced (e.g., [C/M] = 1) models as well, or whether that is something that is beyond the SDSS MARCS grid Korg is drawing from? I ask because I am working with a carbon-enhanced star at [M/H] ~ -3, and it seems sketchy to use a [C/M] = 0 model for that particular case. I imagine this is a somewhat common situation given the increasing frequency of C-enhancement at low metallicity, so if it's even possible, this might be broadly useful? 

Thanks in advance!

**Comment by ajwheeler** [comment]
Hi William,

The short answer is that I don't have any short-term plans to add carbon-enhanced low-metallicity atmospheres to `interpolate_marcs`, but there are a couple caveats that may be relevant to you. 

The first is that the low-metallicity (< -2.5) atmospheres that I'm using from MARCS are "standard composition", meaning that they have [C/M]=0.4.  (The SDSS-specific MARCS grid has variable C but only goes down to [m/H]=-2.5.). This is presumably not close enough to [C/M] ~= -1, obviously.  The second is that you can always download individual model atmosphere files from [the MARCS website](https://marcs.astro.uu.se/) directly and read them into Korg with `read_model_atmosphere`.  If you don't need ultra-precise params you could probably grab a cluster around the parameters you want and use the one that produces the best-fit or do some kind of marginalization over them.

I realized this probably isn't as plug-and-play as would be ideal.  CEMP stars are on my radar, but it's unlikely that I will have a really easy-to-use implementation in the next six months or so, which I'm guessing is the timescale that would be helpful for your current project.

I'll add that if you or someone else wants to take on expanding the low-metallicity grid to include varied carbon I'm happy to provide direction and help get it integrated into Korg, but I certainly don't expect this.  It would amount to downloading the files from MARCS, filling in the gaps, and putting everything in an HDF5 file in the right format.
