### ISSUE TITLE
Enhancement: Suggest "clamp_abundances=True" as part of error message

### ISSUE THREAD

**Issue by svenbuder** [ajwheeler/Korg.jl#290]
I have just tried some extremely CNO-rich stars and went outside of the allowed atmosphere grid:

JuliaError: ArgumentError: Can't interpolate atmosphere grid.  [M/H] is out of bounds.

Looks like you already have implemented the clamp_abundances=True option (just took me a bit of digging in Korg.Fit.synthetic_spectrum, where it's activated by default).

It works now, with the keyword activated, but maybe worth adding to the error message?

**Comment by ajwheeler** [comment]
My current thinking is that `clamp_abundances` should be true by default.  I am about to open a PR that will extend [m/H] down to -5, which is the main case I was worried about handling silently (currently goes only to -2.5).

Thoughts on that as a solution?

**Comment by ajwheeler** [comment]
I though twice about this and and going to keep clamping off by default but make the error message more helpful, as suggested.

**Comment by ajwheeler** [comment]
closed by #291
