### ISSUE TITLE
Highlighting high memory usage for `fit_spectrum`

### ISSUE THREAD

**Issue by shbhuk** [ajwheeler/Korg.jl#300]
Running the Fitting Spectrum example based on Griffith 2022 utilizing `fit_spectrum` seems to require a lot of RAM and gives an OutofMemoryError(). Based on inputs from Adam Wheeler and checking the documentation for `fit_spectrum`, it seems like the culprit might be my Julia version --- `1.9.2`. Will update it to `1.10` and re-try.

Example - https://github.com/ajwheeler/Korg.jl/blob/main/misc/Tutorial%20notebooks/fitting/Fit%20spectrum.ipynb
Documentation - https://ajwheeler.github.io/Korg.jl/stable/API/#Korg.Fit.fit_spectrum

**Comment by ajwheeler** [comment]
Thank you for posting this for others to see.  I'll add that in many cases, you won't get an `OutOfMemoryError`, and may instead see that the code runs much more slowly than it should according to the tutorial.

I'll wait for you to confirm that upgrading to Julia 1.10 solves this before closing.

**Comment by shbhuk** [comment]
I upgraded to Julia 1.10 and reran the example. Firstly, truncating the spectrum to < 5000 A and then comparing the before and after, the memory usage is similar but time taken is halved.

When running the original example (with the full spectra) it runs fine once, but when trying to re-run the exact same cell, gives me the same `OutofMemoryError` while processing the SparseArrays while computing the LSF matrix. 

I was running things locally before shifting to a Linux HPC but it seems like there might be some memory leak somewhere? 

![image](https://github.com/ajwheeler/Korg.jl/assets/25436514/471f4a2a-8832-49a7-894d-2f4c5da37f5f)

Old Julia version: 1.9.2
New Julia version: 1.10.3
Korg version 0.33.0
RAM 32 GB

**Comment by shbhuk** [comment]
Sorry, I should clarify. I haven't yet shifted to an HPC. The plan was to test things locally before batch processing on the HPC. So this could be a Windows peculiarity? 

Project Korg v0.33.0
Status `C:\Users\skanodia\Documents\GitHub\Korg.jl\Project.toml`
  [336ed68f] CSV v0.10.14
  [717857b8] DSP v0.7.9
  [a93c6f00] DataFrames v1.6.1
  [163ba53b] DiffResults v1.1.0
  [442a2c76] FastGaussQuadrature v1.0.2
  [f6369f11] ForwardDiff v0.10.36
  [f67ccb44] HDF5 v0.17.2
  [a98d9a8b] Interpolations v0.15.1
  [d3d80556] LineSearches v7.2.0
  [2774e3e8] NLsolve v4.5.1
  [429524aa] Optim v1.9.4
  [92933f4c] ProgressMeter v1.10.0
  [276daf66] SpecialFunctions v2.4.0
  [90137ffa] StaticArrays v1.9.4
  [592b5752] Trapz v2.0.3
  [37e2e46d] LinearAlgebra
  [44cfe95a] Pkg v1.9.2
  [2f01184e] SparseArrays
  [10745b16] Statistics v1.9.0

**Comment by ajwheeler** [comment]
On #301 (an unrelate4d pull request), both the unit tests running on windows are running out of memory, so it seems very likely that I recently introduced a bug/memory problem which is only triggered on windows.  I'll continue to look into this.

**Comment by shbhuk** [comment]
Okay. Good to know the reason behind this. We will switch to the Linux HPC for now.

Thanks!

**Comment by ajwheeler** [comment]
When Korg 0.35.1 comes out (should be within an hour), I think it will fix this on windows.

**Comment by ajwheeler** [comment]
Closing this as I think it's fixed, but feel free to reopen if that's not the case.
