### ISSUE TITLE
format_A_X with alpha elements

### ISSUE THREAD

**Issue by segasai** [ajwheeler/Korg.jl#319]
Hi, 

I'm trying to make sense of the format_A_X for some alpha element (Ca), and to me it seems to contradict the documentation.
```
julia> Korg.format_A_X(-3,.4)[20]
6.7

julia> Korg.format_A_X(-3,.4,Dict("Ca"=>0))[20]
6.3

julia> Korg.format_A_X(-3,.4,Dict("Ca"=>0.4))[20]
6.7
```

If I understood the documentation correctly the Ca abundance was supposed to be treated as Ca/H. However the numbers imply it is used as Ca/M. Am I missing something here ? 

Also from what i can see for non-alpha elements the behaviour is different.

```

julia> Korg.format_A_X(-3,.4,Dict("B"=>0))[5]
2.7

julia> Korg.format_A_X(-3,.4)[5]
-0.2999999999999998

```

Thanks 
        S

**Comment by segasai** [comment]
Sorry for the noise, I didn't realize the second argument is alpha/H not alpha over M.

**Comment by ajwheeler** [comment]
Yes, apologies for the confusion.  I prefer [alpha/H], but I wanted to match the MARCS atmosphere parameters exactly with `interpolate_marcs`.
