### ISSUE TITLE
Issue with get_metals_h ? 

### ISSUE THREAD

**Issue by segasai** [ajwheeler/Korg.jl#324]
Hi, 
 
I'm trying to understand this part of the code:

https://github.com/ajwheeler/Korg.jl/blob/9e6db774ea2497e347364cbb854946b11374371d/src/synthesize.jl#L453

and I cannot see why this is correct, given the alpha elements are 8:2:22
Shouldn't it be  [3:6 ; 7:2:21 ; 23:MAX_ATOMIC_NUMBER]  or am I missing something ? 

Thanks

**Comment by ajwheeler** [comment]
You are correct.  I am going to fix this and refactor/write tests to try to eliminate this class of bug.

**Comment by ajwheeler** [comment]
#327 fixes this, and will make similar bugs harder to introduce in the future.
