### ISSUE TITLE
Very basic question: is trimming the input linelist to only include relevant line windows an okay way to speed up Korg. synthesize?

### ISSUE THREAD

**Issue by catmanea** [ajwheeler/Korg.jl#357]
Hello!  I have a quick question about the validity of trimming the input linelist for reducing execution time when running Korg.synthesize.

I would like to synthesize 7 spectra with fixed Teff, logg, A(X), vsini, LSF, etc. but varying just A(Fe).  I am using the full Gaia ESO linelist (both atoms and molecules) directly from Heiter+2021.  I have defined 99 Fe windows that I wish to synthesize for each A(Fe) value.  I am working with red giant stellar parameters.

Initially, my first execution of Korg.synthesize took 277s for 1 spectrum.  Subsequent calls took the same amount of time (275s) per spectrum.  When I trim the GaiaESO linelist to only include the 99 Fe windows in question (taking it from 15 million to 1 million entries), the execution time drops to 22s, which is great.  I just wanted to ask--is this the correct approach for reducing Korg.synthesize execution time? Or is trimming the linelist to just the windows of interest (plus a few 0.1's of Angstroms) not the right way to approach this?  Could I be messing up the resulting synthetic spectrum by doing this?  I know this is super basic, but I appreciate the insight!

Thanks so much,
Catherine

**Comment by ajwheeler** [comment]
This can _sometimes_ cause problems in cases where lines whose centers are outside the wavelength region are have wings within it that are non-negligible.  Thankfully it's easy to check this by comparing syntheses done both ways. 

When you synthesize, korg will start by dropping any lines more than 10 \AA outside the wavelength range (this is controllable with the `line_buffer` keyword argument).  If you pre-filter your linelist to include stuff within this distance of any window, you should get the exact same answer with a large speedup.

Btw, you might find it easier to get the GES linelist by doing `Korg.get_GES_linelist()`, but if you already have something working there's no particular advantage to using the built-in copy.

Also, you probably won't run into this doing fits in windows, but there may be a problem with the CH lines in the GES linelist (see #356).  If you do check for this behavior and you don't get it with your custom-loaded linelist, please let me know.
