### ISSUE TITLE
Nan values in the spectrum 

### ISSUE THREAD

**Issue by segasai** [ajwheeler/Korg.jl#363]
Hi, 

I am not quite sure if it's considered a bug or not. But I have a case of a spectrum with a few scattered NaNs in it. In this case I get the electron density warnings and the effective temperature is lowish 4451, so I don't know if NaNs are expected there.
Here's the illustration of the spectrum with nans highlighted.
![image](https://github.com/user-attachments/assets/1b673e0f-e13b-48fc-88df-e685f8e74fdc)

I use korg 0.40.2 with julia 1.10.4.

Below is the python code to reproduce. 
I used a big VALD list I have (if helps I can share it, it's big). I tried the GES one and I don't get NaNs with it.

```python
import numpy as np

def getKorg():
    from juliacall import Main as jl

    jl.seval("using Korg")
    Korg = jl.Korg
    lines = Korg.read_linelist('../all_vald_3000_10000.dat')
    return Korg, lines


def doit(teff, logg, X_H=None, minlam=3500, maxlam=9900):
    Korg, lines = getKorg()
    marcs = Korg.interpolate_marcs(float(teff),
                                   float(logg),
                                   X_H,
                                   clamp_abundances=True)
    spec = Korg.synthesize(
        marcs,
        lines,
        X_H,
        minlam,
        maxlam,
        vmic=1,
        line_buffer=100,
        hydrogen_line_window_size=400,
    )
    wave, spec = np.array(spec.wavelengths), np.array(spec.flux)
    return wave, spec

if __name__ == '__main__':
    teff = 4451.508078978029
    logg = 2.787330711260438
    abund_vec = np.array([
        12., 10.93, 1.66789218, 1.99789218, 3.31789218, 11.35899213,
        7.61283491, 8.53986693, 5.17789218, 7.49418707, 5.89591157, 7.18418707,
        6.98789218, 7.56136204, 5.97789218, 6.79418707, 6.11789218, 5.83418707,
        5.69789218, 7.27814991, 3.78789218, 5.1732481, 4.61789218, 6.25789218,
        5.4260725, 8.06789218, 5.53789218, 6.84789218, 4.82789218, 5.21789218,
        3.49789218, 4.19789218, 2.90789218, 3.94789218, 3.17789218, 3.86789218,
        3.21789218, 3.53789218, 2.82789218, 3.19789218, 2.03789218, 2.53789218,
        -4.38210782, 2.45789218, 1.73789218, 2.27789218, 1.55789218,
        2.38789218, 2.21789218, 2.61789218, 1.61789218, 2.80789218, 2.12789218,
        2.85789218, 1.68789218, 2.1297444, 1.74789218, 2.31789218, 1.19789218,
        2.06789218, -4.38210782, 1.61789218, 1.13789218, 1.72789218,
        0.89789218, 1.75789218, 1.12789218, 1.54789218, 0.61789218, 1.69789218,
        0.67789218, 1.49789218, 0.44789218, 1.72789218, 0.84789218, 1.86789218,
        1.99789218, 2.25789218, 1.62789218, 1.74789218, 1.51789218, 2.61789218,
        1.26789218, -4.38210782, -4.38210782, -4.38210782, -4.38210782,
        -4.38210782, -4.38210782, 0.67789218, -4.38210782, 0.09789218
    ])

    wave, spec = doit(teff, logg, abund_vec, minlan=9000, maxlam=9500)
    print(spec.sum())
```

Thanks

**Comment by ajwheeler** [comment]
This is definitely a bug!  Thanks for reporting.  Do you mind sharing your linelist?  I suspect that this is a edge case that I haven't seen before.

It's suspicious that the nans are near H lines, but it clearly has to have some interaction with the (non-H) lines as well, since Korg doesn't get H lines from the linelist.

If you can reproduce one of the NaNs in a small window, you could give me the partial linelist if that's easier.  Whatever works for you.

**Comment by segasai** [comment]
Great.

Here's the linelist https://datasync.ed.ac.uk/index.php/s/sAuB5N1o0GMLhNs password: korg 

it's a binary 2.5gb file that needs to be deserialized this way:
```
jl.seval('using Serialization') 
lines = jl.seval('open(deserialize, "vald_all_3000_10000.julia.bin")')                                                                                                                                                                                             
```

I tried a smaller subset (i.e. limiting wavelengths to just what's in the window), but that also removes nans, so I'm sharing the whole file.

Thanks!

**Comment by ajwheeler** [comment]
The next issued version of Korg should not have this behavior.  (It was due to consecutive optical depth values being numerically equal very deep in the atmosphere.)   Thanks for reporting!
