### ISSUE TITLE
continuum absorption accuracy 

### ISSUE THREAD

**Issue by ajwheeler** [ajwheeler/Korg.jl#83]
![image](https://user-images.githubusercontent.com/711963/138517668-901e5963-a87a-4758-9b0a-09a07f6c8bdd.png)

There's lots to talk about in the figure comparing the continuum from korg, moog, and TS, but I think the jump in the Korg continuum at 3846\AA (the H2+ bf+ff cutoff, marked with a grey dashed line) is indicating that this source of absorption is overestimated.

Thoughts?

**Comment by ajwheeler** [comment]
I'm continuing to look into this.  I'll definitely look at the MOOG/TS version, but I think a good way to go would be to update our prescription from [Bates 1952](http://articles.adsabs.harvard.edu/pdf/1952MNRAS.112...40B) to [Stancil 1994](http://articles.adsabs.harvard.edu/pdf/1994ApJ...430..360S). This will also give us coverage down to 500 Å, although the temp lower bound will go up (perhaps, we could interpolate?).  It's also 40 years more recent, and presumably much more accurate.

Also, I didn't realize that H2+ bf refers to H2 II + gamma -> H I + H II !  That should definitely be documented! (Sorry if I missed it.)

**Comment by ajwheeler** [comment]
To be clear, is TS using the data form the Mihalas paper?  I can't actually find the part of the code where they do this...

**Comment by ajwheeler** [comment]
OK, so the new (Stancil) implementation reproduces the continuum offset with other codes, as expected, since it matches the Bates/Gray values.  The good news is that we don't have the problematic discontinuity around 3850 \AA, where the old values stopped.
![image](https://user-images.githubusercontent.com/711963/142253994-6c72d4ba-7b7d-42f9-9605-41cdee2f41db.png)
![image](https://user-images.githubusercontent.com/711963/142254019-a8bb6447-2abc-4e5c-bbea-0e29139bd247.png)

Manually turning it off gets a closer match, but I'm now pretty convinced we aren't actually doing anything wrong RE H2plus.  It may be that something else is overestimated, or that the other codes are underestimating somthing.

**Comment by ajwheeler** [comment]
I've checked that the ff contribution from H2plus is very small and does not account for the discrepancy.

**Comment by ajwheeler** [comment]
Comparisons with Turbospectrum in other stars have suggested that at least one source of continuum opacity is significantly overestimated in Korg.  (An alternative explanation is that there is something wrong with my radiative transfer.  I'm not ruling this out.  I suppose it could also be the molecular equilibrium but I wouldn't bet on it.)

Here's an underestimated (wrt TS) continuum for two giants:
![image](https://user-images.githubusercontent.com/711963/144653748-3d0288b9-4145-4a72-a22b-480a433267c4.png)
![image](https://user-images.githubusercontent.com/711963/144653767-6bf781fc-c6b0-4abb-8dfd-2a02b3e27088.png)


This persists if H- bf is the _only source_ turned on for Korg.
![image](https://user-images.githubusercontent.com/711963/144653656-1fcd32d2-8a52-4497-9554-be23f560b651.png)
![image](https://user-images.githubusercontent.com/711963/144653664-75257c47-a422-4780-bd1d-d17ced316714.png)
This suggests that there is a problem with that particular source.  TS is using the same table of cross-sections (Wishart+ 1979), so that's not the problem.  There could be a disparity arising from how n(H-) is calculated.  TS uses [Mihalas 1967](https://ui.adsabs.harvard.edu/abs/1967MComP...7....1M/abstract), which I haven't found a PDF for...

**Comment by mabruzzo** [comment]
This looks crazy!

**Comment by ajwheeler** [comment]
OK, so turbospec adjusts the ionization energy of H- for pressure, according to this paper: https://articles.adsabs.harvard.edu/pdf/1969tons.conf..143T.  I'm not sure if this is a large enough effect to explain the difference, but I'm looking into it.  It's probably something we should be aware of anyway.

**Comment by ajwheeler** [comment]
An overview of this effect is found on Hubeny and Mihalas p244-246, which states that  ionization potentials can be adjusted by `3e-8 * Z * ne^0.5 T^-0.5 eV` as a rough approximation. 

```julia
julia> [3e-8  * sqrt(l.electron_number_density / l.temp) for l in atm.layers]
 3.338923987225036e-6
 3.98622586156897e-6
 4.746751058123049e-6
 5.628540558561197e-6
 6.649828953533077e-6
 7.826763746735217e-6
 9.165571895018155e-6
 1.0669809772082763e-5
 1.2337084775531654e-5
 1.4177154541496423e-5
 1.6225400209165468e-5
 1.7291895559478315e-5
 1.843716023129176e-5
 ⋮
 0.0009883337060364432
 0.0011845003364186083
 0.001384572744372603
 0.0015874316679815375
 0.0017938935198369107
 0.002004763014170044
 0.002221103664318355
 0.0026648894546756753
 0.0031523364249812463
 0.0036892123015088555
 0.004280991706155335
 0.00493208728816118
```
Too small to be the cause of this difference.

**Comment by ajwheeler** [comment]
I've tracked down some problems with how we were interpolated model atmospheres, and am am going to switch Korg over to use different atmosphere params internally (see #97).  This accounts for some discrepancy between Korg and Moog/TS.  I still don't understand entirely what's going on.  

In the meantime, here's a plot comparing alpha extracted from Moog and Korg for the sun at each layer in the atmosphere.
![image](https://user-images.githubusercontent.com/711963/147784866-95ee455b-677c-4764-82e5-1ba0dce03882.png)

**Comment by ajwheeler** [comment]
With, #97, the continua look like this:
![image](https://user-images.githubusercontent.com/711963/148424350-4c4f261e-4966-4612-87b7-631de4af10a9.png)
![image](https://user-images.githubusercontent.com/711963/148424364-24c73a1e-629e-44e2-a656-4c50357a9aa1.png)
![image](https://user-images.githubusercontent.com/711963/148424371-6cfce17b-10bf-46c1-bbe8-237404ac146b.png)
![image](https://user-images.githubusercontent.com/711963/148424383-2cfe3f70-4614-4b18-b214-2cb01c1652ab.png)

Note that our continuum absorption is still larger than Moog's, but it matters less with the renormalization to the model atmosphere tau, and it's not clear to me that Korg is less correct.  I'll leave this issue open, since this remains an interesting thing to investigate, but it's no longer critical.

**Comment by mabruzzo** [comment]
So I have a naive question, why is there any disagreement at all at 5000 Angstroms? Aren't all of the code effectively using the same opacity at that wavelength? 

Or do they all agree exactly when you consider the full spectra (when you additionally include the line list).

**Comment by ajwheeler** [comment]
That is the naive expectation, yes. I think the differences come down to
slight differences in how radiative transfer is done, but I could be wrong.

**Comment by ajwheeler** [comment]
I got around to comparing our opacities to those form MARCS (which are the same as those from turbospectrum).  Here's the same plot, indicating  that we are doing pretty well.
![download](https://user-images.githubusercontent.com/711963/188731959-e99a88be-5a40-4ff5-bc40-c027ab6de142.png)
same thing with compressed colorbar:
![download-1](https://user-images.githubusercontent.com/711963/188732298-b84e5e32-ca8b-410d-9c78-09066052902c.png)

**Comment by ajwheeler** [comment]
A view extending down to lower wavelengths:
![download-2](https://user-images.githubusercontent.com/711963/188749440-984859be-0ec8-4a84-afdf-b1be3dfa8876.png)

**Comment by ajwheeler** [comment]
By the way, this is what bf metal absorption looks like.  It's not at the right wavelength and tau (nor is it strong enough) to account for the discrepancy.

![download-4](https://user-images.githubusercontent.com/711963/188896220-87fb1c25-012f-4361-a6d1-c69b2d382a20.png)

**Comment by mabruzzo** [comment]
That is fascinating - although the y-axis is a little confusing. Could you remind me what that means again?

**Comment by ajwheeler** [comment]
It's log(optical depth), so the top (bottom) of the plot is the top (bottom) of the atmosphere.

**Comment by ajwheeler** [comment]
Looking at the MOOG output, it turns out that the difference *is* due to metal opacity, specifically Al I.  Currently trying to figure out why we don't reproduce it.

**Comment by mabruzzo** [comment]
Fascinating. I have a faint recollection of seeing Al I opacity in the MOOG source code, and seem to recall that it was:
- overly simplistic
- somewhat unclear publication it came from

**Comment by ajwheeler** [comment]
I believe all the sources in MOOG are form ATLAS.

From the ATLAS report:
![Screen Shot 2022-09-07 at 1 25 33 PM](https://user-images.githubusercontent.com/711963/188941247-23cbbb88-af8e-473d-abb1-a23ec597e92a.png)

MOOG implementation, which I think it from the ATLAS source.
```fortran
      subroutine opacAl1
c******************************************************************************
c     This routine computes the bound-free absorption due to Al I.
c******************************************************************************

      implicit real*8 (a-h,o-z)
      include 'Atmos.com'
      include 'Kappa.com'
   
      do i=1,ntau
         if (freq .ge. 1.443d15) then
            aAl1(i) = 6.5d-17*(1.443d15/freq)**5*6.*
     .                numdens(5,1,i)/u(13,1,i)
         endif
      enddo

      return
      end
```

**Comment by ajwheeler** [comment]
Ok, so I've done some work on the metal bf opacities.  Currently I'm only including just using neutral C, Mg, Al, and Si.  These are what's in MOOG (minus Fe) and they are also the species  that MARCS does an empirical energy level adjustment for.  I'm also doing the adjustment, though I'm doing all energy levels, while MARCS only did those in the UV (?).

With that change, the delta from MARCS opacs looks like this:
![download-1](https://user-images.githubusercontent.com/711963/189368866-a62b5368-a3db-4b24-932c-12230553a791.png)
Our continuum looks like this:
![download](https://user-images.githubusercontent.com/711963/189368941-0699d24d-9e3d-40d7-a4e6-83e7b5e3b324.png)


There are two possible things going on with this.
- Our metal bf opacities are very spiky, possibly too much so.  I did convolve them with a small doppler profile, to smear the edges a bit, but perhaps MARCS smears them more?  We have more "features" in the UV than Turbospectrum does, and our alpha is overestimated relative to MARCS at the energy "edges", suggesting this is true.  Another possibility is that I have some sort of bug which "compresses" the cross-section for each electron configuration in wavelength space, making it spikier (???)

and/or
- I just need to add more metals.  More blanketing would make the UV less "spiky" maybe, and since we are using NORAD for some species, it's not surprising if our metal opacities are higher than MARCS's in some places.

**Comment by mabruzzo** [comment]
> Our metal bf opacities are very spiky, possibly too much so. I did convolve them with a small doppler profile, to smear the edges a bit, but perhaps MARCS smears them more? We have more "features" in the UV than Turbospectrum does, and our alpha is overestimated relative to MARCS at the energy "edges", suggesting this is true. Another possibility is that I have some sort of bug which "compresses" the cross-section for each electron configuration in wavelength space, making it spikier (???)

I'm fairly confident that we aren't "compressing" the cross-sections in wavelength space. A while back I proved that we were doing things correctly by comparing OP opacities for hydrogenic species to the analytic formula. (If there is a bug, it's related to multi-electron atoms or  it appeared after I performed that test)

I'm fairly confident the issue is related to smoothing. I seem to recall that the MARCS paper explicitly states that they smoothed opacities. I seem to recall that they were vague about exactly how they smoothed them (but I think they implied that they wanted to smear to remove resonance spikes).

**Comment by ajwheeler** [comment]
This makes sense to me.   I added in iron as well, and got this:
![download-2](https://user-images.githubusercontent.com/711963/189429187-fda7161f-ba1e-43e7-88df-01c8d3b7cf7b.png)
![download-3](https://user-images.githubusercontent.com/711963/189429186-5552ddec-362a-42ea-a6be-aff755976b18.png)

I can definitely imagine that adding back all the species in MARCS and smearing them a bit will get up pretty close to the MARCS opacs.  (Though they do include some lines, so it's OK if they still have more absorption.)

**Comment by ajwheeler** [comment]
I'm going to close this since the topic of conversation has changed significantly since I started it and the original issue is solved.  Future discussion of continuum absorption can happen in more specific issues.

**Comment by ajwheeler** [comment]
It's log(optical depth at 5000 Angstroms).
